# Generated by Django 5.0.1 on 2024-01-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(help_text='The name of the Enterprise.', max_length=100)),
                ('Cedula_Juridica', models.CharField(help_text='The number of the RIF.', max_length=50)),
                ('Direccion', models.CharField(help_text='Address.', max_length=300)),
                ('Ciudad', models.CharField(help_text='City.', max_length=50)),
                ('Estado', models.CharField(help_text='State.', max_length=50)),
                ('Pais', models.CharField(help_text='Country.', max_length=50)),
                ('Zip_code', models.IntegerField(help_text='zipcode')),
                ('Telefono', models.CharField(help_text='telepohone number', max_length=15)),
                ('Correo', models.EmailField(help_text='email of the company', max_length=254)),
                ('Pagina_web', models.URLField(help_text='Pagina Oficial de la compania', max_length=300)),
                ('Representante', models.CharField(help_text='The name of the representante', max_length=100)),
                ('Representante_email', models.EmailField(help_text='email of the representante', max_length=254)),
                ('Encargado_RRHH', models.CharField(help_text='The name of the Encargado RRHH', max_length=100)),
                ('Encargado_RRHH_email', models.EmailField(help_text='email of the Encargado RRHH', max_length=254)),
            ],
        ),
    ]
