# Generated by Django 5.0.1 on 2024-04-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0005_archivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='Pagado_por_Empresa_o_CCSS',
            field=models.FileField(default='empresa', upload_to=''),
        ),
    ]
