# Generated by Django 5.0.1 on 2024-04-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0006_permisos_pagado_por_empresa_o_ccss'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIPE_Mensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=60)),
                ('ced_jur', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('mes', models.CharField(max_length=20)),
                ('fecha_sipe', models.DateField(default='2024-01-15')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('sexo', models.CharField(max_length=15)),
                ('tipo_docu', models.CharField(max_length=20)),
                ('nro_identificacion', models.CharField(max_length=20)),
                ('seguro_social', models.CharField(max_length=30)),
                ('total_sueldo', models.FloatField(default=0)),
                ('total_vacaciones', models.FloatField(default=0)),
                ('total_xxi', models.FloatField(default=0)),
                ('total_sueldo_ajustado', models.FloatField(default=0)),
                ('total_ss', models.FloatField(default=0)),
                ('SS_Patron', models.FloatField(default=0)),
                ('total_se', models.FloatField(default=0)),
                ('SE_Patron', models.FloatField(default=0)),
                ('total_dtm', models.FloatField(default=0)),
                ('DTM_SS_Patro', models.FloatField(default=0)),
                ('total_islr', models.FloatField(default=0)),
                ('total_rp', models.FloatField(default=0)),
                ('Total_Gasto_Patron', models.FloatField(default=0)),
                ('total_pago_Sipe', models.FloatField(default=0)),
                ('fecha_entrada', models.CharField(max_length=60)),
                ('fecha_salida', models.CharField(max_length=60)),
                ('notifi_vacaciones', models.CharField(max_length=120)),
            ],
        ),
    ]
