# Generated by Django 5.0.1 on 2024-04-09 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0007_sipe_mensual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='Usuario_permiso',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(default='Activo', max_length=20)),
                ('nivel_seguridad', models.IntegerField(default=5)),
                ('Colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GOcs.colaboradores')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GOcs.info_clientes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
