# Generated by Django 5.0.1 on 2024-04-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0008_colaboradores_usuario_permiso_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Company',
        ),
    ]
