# Generated by Django 5.0.1 on 2024-04-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0011_userprofile_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fecha_creacion',
            field=models.DateField(default='2024-01-02'),
        ),
    ]
