# Generated by Django 5.0.1 on 2024-04-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0012_userprofile_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Administrador',
            field=models.CharField(default='Administrador', max_length=20),
        ),
    ]
