# Generated by Django 5.0.1 on 2024-04-10 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0013_userprofile_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='Quien_agrego_Jornada',
            field=models.CharField(default='Administrador', help_text='Quien agrego la jornada', max_length=50),
        ),
        migrations.CreateModel(
            name='Seguimiento_Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_seguimiento', models.CharField(help_text='tipo seguimiento.', max_length=50)),
                ('SUB_Tipo_seguimiento', models.CharField(help_text='tipo seguimiento.', max_length=50)),
                ('comentario', models.CharField(help_text='tipo seguimiento.', max_length=200)),
                ('Fecha_novedad', models.DateField(default='2024-01-15')),
                ('hora_novedad', models.CharField(help_text='tipo seguimiento.', max_length=20)),
                ('Colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GOcs.colaboradores')),
            ],
        ),
    ]
