# Generated by Django 5.0.1 on 2024-04-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0015_alter_seguimiento_actividad_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_departamento', models.CharField(help_text='Crear nombre departamento', max_length=100)),
                ('Comentario', models.CharField(help_text='Crear comentario departamento', max_length=200)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GOcs.info_empresa')),
            ],
        ),
    ]
