# Generated by Django 5.0.1 on 2024-04-15 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0018_liquidaciones_clientes_descuento_acreedores_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos_Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_Subido', models.DateField(default='2024-01-01')),
                ('Nombre_Archivo', models.CharField(max_length=255)),
                ('Comentario_Archivo', models.CharField(max_length=255)),
                ('Archivo', models.FileField(upload_to='')),
                ('Colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GOcs.colaboradores')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GOcs.info_empresa')),
                ('Quien_lo_subio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GOcs.userprofile')),
            ],
        ),
    ]
