# Generated by Django 5.0.1 on 2024-05-01 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0020_planificacion_almuerzo_bool_domingo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acreedores_quincena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia_Inicio_cobro', models.DateField(default='2024-01-01', help_text='dia entrada')),
                ('Periodo_Cobro', models.CharField(default='Q1-1-2023', help_text='Quien agrego la jornada', max_length=50)),
                ('Monto_periodo', models.FloatField()),
                ('Nro_Cuota', models.IntegerField()),
                ('Total_monto_abonado', models.FloatField()),
                ('Acreedores', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GOcs.acreedores')),
            ],
        ),
    ]
