# Generated by Django 5.0.1 on 2024-05-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0021_acreedores_quincena'),
    ]

    operations = [
        migrations.AddField(
            model_name='acreedores_quincena',
            name='Realizo_Cobreo',
            field=models.BooleanField(default=False),
        ),
    ]
