# Generated by Django 5.0.1 on 2024-05-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0022_acreedores_quincena_realizo_cobreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acreedores_quincena',
            name='Tipo_Operacion',
            field=models.CharField(default='Planilla', help_text='Planilla o Liquidacion', max_length=50),
        ),
    ]
