# Generated by Django 5.0.1 on 2024-05-01 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOcs', '0023_acreedores_quincena_tipo_operacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cerrar_Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo', models.CharField(default='Q1-02-2020', help_text='QUE QUATER ESTA', max_length=15)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='GOcs.info_empresa')),
            ],
        ),
    ]
